apps/encuestas/urls.py
from django.urls import path
from apps.encuestas.views import agregar_encuesta_mujer, consultar_encuesta_mujer, agregar_encuesta_hombre, index, \
    consultar_encuesta_hombre, modificar_encuesta_mujer, modificar_encuesta_hombre

urlpatterns = [
    path('', index, name='index'),
    path('agregar_encuesta_mujer/', agregar_encuesta_mujer, name='agregar_encuesta_mujer'),
    path('consultar_encuesta_mujer/', consultar_encuesta_mujer, name='consultar_encuesta_mujer'),
    path('modificar_encuesta_mujer/<id_encuesta>/', modificar_encuesta_mujer, name='modificar_encuesta_mujer'),
    path('agregar_encuesta_hombre/', agregar_encuesta_hombre, name='agregar_encuesta_hombre'),
    path('consultar_encuesta_hombre/', consultar_encuesta_hombre, name='consultar_encuesta_hombre'),
    path('modificar_encuesta_hombre/<id_encuesta>/', modificar_encuesta_hombre, name='modificar_encuesta_hombre'),
]

encuestas_vif/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encuestas/', include('apps.encuestas.urls')),
    path('', include('apps.login.urls')),
    path('select2/', include('django_select2.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/encuestas/models.py
from datetime import date, datetime
from django.db import models


class DatosMujeres(models.Model):

    MEDICION_CHOICES = (
        ('1', 'Medicion 1 (Linea Base)'),
        ('2', 'Medicion 2 (Salida)'),
        ('3', 'Medicion 3 (Seguimiento)')
    )

    INSTITUCION_SALUD_CHOICES = (
        ('1', 'ESE Ladera de Cali'),
        ('2', 'Hospital Rubén Cruz de Tuluá'),
        ('3', 'IPS Renaseres - Piloto Hombres'),
        ('4', 'Hospital Divino Niño Buga'),
        ('5', 'Fundacion FAMI SQ - Piloto Hombres'),
        ('6', 'ESE Centro Cali'),
        ('7', 'Hospital Departamental Tomas Uribe Uribe'),
        ('8', 'Hospital Piloto Jamundí'),
    )

    CIUDAD_CHOICES = (
        ('1', 'Cali'),
        ('2', 'Tuluá'),
        ('3', 'Buga'),
        ('4', 'Santander de Quilichao')
    )

    ESTADO_CIVIL_CHOICES = (
        ('1', 'Soltera'),
        ('2', 'Casada'),
        ('3', 'Divorciada'),
        ('4', 'Separada'),
        ('5', 'Viuda'),
        ('6', 'Unión Libre')
    )

    SITUACION_SENTIMENTAL_CHOICES = (
        ('1', 'Con pareja'),
        ('2', 'Sin pareja')
    )

    ESCOLARIDAD_CHOICES = (
        ('1', 'Sin escolaridad'),
        ('2', 'Primaria'),
        ('3', 'Secundaria'),
        ('4', 'Técnico'),
        ('5', 'Universidad')
    )

    SI_NO_CHOICES = (
        ('1', 'Si'),
        ('0', 'No'),
    )

    DISCAPACIDAD_CHOICES = (
        ('1', 'Motora'),
        ('2', 'Visual'),
        ('3', 'Mental'),
        ('4', 'Auditiva'),
        ('5', 'Del lenguaje')
    )

    SITUACION_LABORAL_CHOICES = (
        ('1', 'Trabajo de tiempo completo'),
        ('2', 'Trabajo de medio tiempo'),
        ('3', 'Independiente'),
        ('4', 'Estudia y no trabaja'),
        ('5', 'Ni trabaja, ni estudia')
    )

    TIPO_SUSTANCIA_CHOICES = (
        ('1', 'Marihuana'),
        ('2', 'Cocaína'),
        ('3', 'Perico'),
        ('4', 'Otro')
    )

    TIPO_VIVIENDA_CHOICES = (
        ('1', 'Propia'),
        ('2', 'Rentada/Alquilada'),
        ('3', 'Prestada'),
        ('4', 'Invadida')
    )

    TIPO_REGIMEN_SALUD_CHOICES  = (
        ('1', 'Contributivo'),
        ('2', 'Subsidiado'),
        ('3', 'Vinculado'),
        ('4', 'Otro')
    )

    TIPO_RELACION_AGRESOR_CHOICES = (
        ('1', 'Pareja actual EN convivencia'),
        ('2', 'Pareja actual SIN convivencia'),
        ('3', 'Pareja anterior EN convivencia'),
        ('4', 'Pareja anterior SIN convivencia'),
        ('5', 'Otro')
    )

    ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES = (
        ('0', 'Ninguna'),
        ('1', 'Pocas veces'),
        ('2', 'Varias veces'),
        ('3', 'Muchas veces')
    )

    ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_CHOICES = (
        ('4', 'Muy de acuerdo'),
        ('3', 'De acuerdo'),
        ('2', 'En desacuerdo'),
        ('1', 'Muy en desacuerdo')
    )

    ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_INVERTIDA_CHOICES = (
        ('1', 'Muy de acuerdo'),
        ('2', 'De acuerdo'),
        ('3', 'En desacuerdo'),
        ('4', 'Muy en desacuerdo')
    )

    ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_CINCO_CHOICES = (
        ('5', 'Muy de acuerdo'),
        ('4', 'De acuerdo'),
        ('3', 'Ni de acuerdo, ni en desacuerdo'),
        ('2', 'En desacuerdo'),
        ('1', 'Muy en desacuerdo')
    )

    ESCALA_NINGUNA_A_EXTREMA_CHOICES = (
        ('1', 'Ninguna'),
        ('2', 'Leve'),
        ('3', 'Moderada'),
        ('4', 'Severa'),
        ('5', 'Extrema/No puede hacerlo')
    )

    ESCALA_DEPENDENCIA_EMOCIAL_CHOICES = (
        ('1', 'Completamente falso'),
        ('2', 'Mayor parte falso'),
        ('3', 'Ligeramente mas verdadero'),
        ('4', 'Moderadamente verdadero'),
        ('5', 'Mayor parte verdadero'),
        ('6', 'Me describe perfectamente')
    )

    ESCALA_VIOLENCIA_CHOICES = (
        ('1', 'Nunca'),
        ('2', 'Una vez'),
        ('3', 'Algunas veces'),
        ('4', 'Muchas veces')
    )

    ESCALA_NUNCA_A_SIEMPRE_CHOICES = (
        ('1', 'Nunca'),
        ('2', 'Pocas veces'),
        ('3', 'Algunas veces'),
        ('4', 'Muchas veces'),
        ('5', 'Siempre')
    )

    hora_inicio = models.TimeField(default=datetime.now())
    hora_final = models.TimeField()
    fecha_encuesta = models.DateField(default=date.today)
    id_paciente = models.CharField(max_length=100)
    id_encuestador = models.CharField(max_length=100)
    medicion = models.CharField(max_length=100, choices=MEDICION_CHOICES)
    institucion_salud = models.CharField(max_length=100, choices=INSTITUCION_SALUD_CHOICES)
    servicio_remitente = models.CharField(max_length=100)
    a1_ciudad = models.CharField(max_length=100, choices=CIUDAD_CHOICES)
    a2_barrio = models.CharField(max_length=100)
    a3_direccion = models.CharField(max_length=100)
    a4_edad = models.IntegerField()
    a5_estado_civil = models.CharField(max_length=100, choices=ESTADO_CIVIL_CHOICES)
    a6_situacion_sentimental = models.CharField(max_length=100, choices=SITUACION_SENTIMENTAL_CHOICES)
    a7_escolaridad = models.CharField(max_length=100, choices=ESCOLARIDAD_CHOICES)
    a8_discapacidad = models.CharField(max_length=100, choices=SI_NO_CHOICES)
    a8a_tipo_discapacidad = models.CharField(max_length=100, choices=DISCAPACIDAD_CHOICES, blank=True)
    a9_situacion_laboral = models.CharField(max_length=100, choices=SITUACION_LABORAL_CHOICES)
    a10_consume_cigarrillo = models.CharField(max_length=100, choices=SI_NO_CHOICES)
    a11_consume_alcohol = models.CharField(max_length=100, choices=SI_NO_CHOICES)
    a12_consume_tipo_sustancia = models.CharField(max_length=100, choices=SI_NO_CHOICES)
    a12a_tipo_sustancia = models.CharField(max_length=100, choices=TIPO_SUSTANCIA_CHOICES, blank=True)
    a12b_otro_tipo_sustancia = models.CharField(max_length=100, blank=True)
    b1_num_personas_hogar = models.IntegerField()
    b2_esposo = models.BooleanField()
    b2_companero = models.BooleanField()
    b2_hijos = models.BooleanField()
    b2_sobrinos = models.BooleanField()
    b2_primos = models.BooleanField()
    b2_suegros = models.BooleanField()
    b2_ex_esposo = models.BooleanField()
    b2_ex_companero = models.BooleanField()
    b2_tios = models.BooleanField()
    b2_hermanos = models.BooleanField()
    b2_abuelos = models.BooleanField()
    b2_conocidos = models.BooleanField()
    b2_otro = models.BooleanField()
    b2_otro_especificado = models.CharField(max_length=100, blank=True)
    b3_num_personas_aportan_hogar = models.IntegerField()
    b4_num_personas_dependen_dentro = models.IntegerField()
    b4_num_personas_dependen_fuera = models.IntegerField()
    b5_tipo_de_vivienda = models.CharField(max_length=100, choices=TIPO_VIVIENDA_CHOICES)
    b6_regimen_salud = models.CharField(max_length=100, choices=TIPO_REGIMEN_SALUD_CHOICES)
    b6_otro_especificado = models.CharField(max_length=100, blank=True)
    c1_relacion_agresor = models.CharField(max_length=100, choices=TIPO_RELACION_AGRESOR_CHOICES)
    c1_otro_especificado = models.CharField(max_length=100, blank=True)
    d1_sentir_susto = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d2_sentir_miedo = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d3_sentir_desmayo = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d4_sentir_nervios = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d5_sentir_corazon = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d6_sentir_tembladera = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d7_sentir_tension = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d8_dolor_cabeza = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d9_sentir_terror = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    d10_sentir_agitada = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    e1_digna_aprecio = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_CHOICES)
    e2_cualidades_buenas = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_CHOICES)
    e3_capaz_hacer_cosas = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_CHOICES)
    e4_actitud_positiva = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_CHOICES)
    e5_satisfecha = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_CHOICES)
    e6_no_estar_orgullosa = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_INVERTIDA_CHOICES)
    e7_inclino_fracasada = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_INVERTIDA_CHOICES)
    e8_sentir_respesto_propio = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_INVERTIDA_CHOICES)
    e9_pensar_ser_inutil = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_INVERTIDA_CHOICES)
    e10_no_buena_persona = models.CharField(max_length=100, choices=ESCALA_MUY_DEACUERDO_MUY_DESACUERDO_INVERTIDA_CHOICES)
    f1_sentirse_sin_energia = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    f2_culparse_por_algo = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    f3_llorar_facilmente = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    f4_perdida_sexual = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    f5_poco_apetito = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    f6_dificultad_dormir = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)
    f7_sentir_sin_esperanza = models.CharField(max_length=100, choices=ESCALA_NINGUNA_A_MUCHAS_VECES_CHOICES)

apps/encuestas/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect
# Create your views here.
from apps.encuestas.forms import AgregarEncuestaMujerForm, AgregarEncuestaHombreForm
from apps.encuestas.models import DatosMujeres, DatosHombres


@login_required
def index(request):
    return render(request, 'encuesta/index.html')

@login_required
def agregar_encuesta_mujer (request):
    form = AgregarEncuestaMujerForm()
    if request.method == 'POST':
        form = AgregarEncuestaMujerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Encuesta registrada exitosamente')
            return redirect(consultar_encuesta_mujer)
        else:
            print(form.errors)
            messages.error(request, 'No se pudo registrar la encuesta')
    contexto = {'form': form}
    return render(request, 'encuesta/agregar_encuesta_mujer.html', contexto)

@login_required
def agregar_encuesta_hombre(request):
    form = AgregarEncuestaHombreForm()
    if request.method == 'POST':
        form = AgregarEncuestaHombreForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Encuesta registrada exitosamente')
            return redirect(consultar_encuesta_hombre)
        else:
            print(form.errors)
            messages.error(request, 'No se pudo registrar la encuesta')
    contexto = {'form': form}
    return render(request, 'encuesta/agregar_encuesta_hombre.html', contexto)

@login_required
def consultar_encuesta_mujer(request):
    datos = list(DatosMujeres.objects.all())
    contador = 0
    contexto = {'datos': datos, 'contador': contador}
    return render(request, 'encuesta/consultar_encuesta_mujer.html', contexto)

@login_required
def consultar_encuesta_hombre(request):
    datos = list(DatosHombres.objects.all())
    contador = 0
    contexto = {'datos': datos, 'contador': contador}
    return render(request, 'encuesta/consultar_encuesta_hombre.html', contexto)


@login_required
def modificar_encuesta_mujer(request, id_encuesta):
    datos = DatosMujeres.objects.get(id=id_encuesta)
    form = AgregarEncuestaMujerForm(instance=datos)
    if request.method == 'POST':

        form = AgregarEncuestaMujerForm(request.POST, instance=datos)
        if form.is_valid():
            form.save()
            messages.success(request, 'Encuesta Modificada exitosamente')
            return redirect(consultar_encuesta_mujer)
        else:
            print(form.errors)
            messages.error(request, 'No se pudo modificar la encuesta')
    contexto = {'form': form}
    return render(request, 'encuesta/modificar_encuesta_mujer.html', contexto)

@login_required
def modificar_encuesta_hombre(request, id_encuesta):
    datos = DatosHombres.objects.get(id=id_encuesta)
    form = AgregarEncuestaHombreForm(instance=datos)
    if request.method == 'POST':

        form = AgregarEncuestaHombreForm(request.POST, instance=datos)
        if form.is_valid():
            form.save()
            messages.success(request, 'Encuesta Modificada exitosamente')
            return redirect(consultar_encuesta_hombre)
        else:
            print(form.errors)
            messages.error(request, 'No se pudo modificar la encuesta')
    contexto = {'form': form}
    return render(request, 'encuesta/modificar_encuesta_hombre.html', contexto)

apps/encuestas/templates/encuesta/consultar_encuesta_hombre.html
{% extends 'base/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}


{% block title_block %} Consultar Encuesta Hombre {% endblock %}



{% block title_content_block %}Consultar Encuesta Hombre - VIF {% endblock %}

{% block css_block %}
    
    <link rel="stylesheet" href="{% static 'css/css_personalizados.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

{% endblock %}

{% block content_block %}
    <div class="container">
    <div class="row">
        <div class="col-md-12 ">
            <div class="table-responsive-lg">
                <table id="myTable" class="table table-striped">
                  <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col" style="text-align: center">Fecha</th>
                        <th scope="col" style="text-align: center">Encuestador</th>
                        <th scope="col" style="text-align: center">Paciente</th>
                        <th scope="col" style="text-align: center">Medicion</th>
                        <th scope="col" style="text-align: center">Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for dato in datos %}
                          <tr>
                              <th scope="row">{{ contador|add:1 }}</th>
                              <td style="text-align: center"> {{ dato.fecha_encuesta }}</td>
                              <td style="text-align: center"> {{ dato.id_encuestador }}</td>
                              <td style="text-align: center"> {{ dato.id_paciente }}</td>
                              <td style="text-align: center"> {{ dato.get_medicion_display }}</td>
                               <td><a href="{% url 'modificar_encuesta_hombre' dato.id %}"
                                       class="btn btn-block btn-warning btn-sm">Modificar</a>
                              </td>
                          </tr>
                        {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

{% block js_block %}

    <!-- DataTables -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>

    $(function () {
        $('#myTable').DataTable(
            {
                    "language": {
                        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
                    }
                }
        );
    } );
    </script>
{% endblock %}

apps/encuestas/templates/encuesta/consultar_encuesta_mujer.html
{% extends 'base/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}


{% block title_block %} Consultar Encuesta Mujer {% endblock %}



{% block title_content_block %}Consultar Encuesta Mujer - VIF{% endblock %}

{% block css_block %}
    
    <link rel="stylesheet" href="{% static 'css/css_personalizados.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

{% endblock %}

{% block content_block %}
    <div class="container">
    <div class="row">
        <div class="col-md-12 ">
            <div class="table-responsive-lg">
                <table id="myTable" class="table table-striped">
                  <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col" style="text-align: center">Fecha</th>
                        <th scope="col" style="text-align: center">Encuestador</th>
                        <th scope="col" style="text-align: center">Paciente</th>
                        <th scope="col" style="text-align: center">Medicion</th>
                        <th scope="col" style="text-align: center">Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for dato in datos %}
                          <tr>
                              <th scope="row">{{ contador|add:1}}</th>
                              <td style="text-align: center"> {{ dato.fecha_encuesta }}</td>
                              <td style="text-align: center"> {{ dato.id_encuestador }}</td>
                              <td style="text-align: center"> {{ dato.id_paciente }}</td>
                              <td style="text-align: center"> {{ dato.get_medicion_display }}</td>
                              <td><a href="{% url 'modificar_encuesta_mujer' dato.id %}"
                                       class="btn btn-block btn-warning btn-sm">Modificar</a>
                              </td>
                          </tr>

                        {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

{% block js_block %}

    <!-- DataTables -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
    $(function () {
        $('#myTable').DataTable(
            {
                    "language": {
                        "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
                    }
                }
        );
    } );
    </script>
{% endblock %}

apps/encuestas/templates/encuesta/index.html
{% extends 'base/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title_block %}Index{% endblock %}


{% block title_content_block %}Encuestas VIF{% endblock %}

{% block content_block %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="text-center font-weight-light"> Sistema diseñado por el área de sistemas del instituto CISALVA
                    para la gestión de encuestas del proyecto de violencia intrafamiliar VIF</p>
            </div>

        </div>
    </div>
{% endblock %}